### PR TITLE
Change defaults of trace and diagonal to `axis1=-2`, `axis2=-1`.

### PR DESCRIPTION
**Pull request by Lezcano**
As per the title.

Fixes https://github.com/data-apis/array-api/issues/215

Also corrected a small errata.

cc @rgommers @asmeurer

### CODE REVIEW

**Comment by asmeurer** [comment]
The 0 and 1 defaults come from NumPy. I'm not sure why NumPy uses the first two axes instead of the last two.

**Review by rgommers — APPROVED** [review]
Thanks @Lezcano! I agree that this makes sense for consistency. I searched the NumPy issue tracker and PRs, and it hasn't been discussed before. 

Let's leave it open for at least 3-4 days, given that it's an API change.

**Comment by leofang** [comment]
Sorry @Lezcano, I overlooked this PR and [left a question](https://github.com/data-apis/array-api/issues/215#issuecomment-886912690) in the original issue.

**Comment by rgommers** [comment]
Superceded by gh-241. Thanks @Lezcano and @asmeurer

**Pull request closed without merging**
