### PR TITLE
Fix `matmul` formatting

### PR DESCRIPTION
**Pull request by leofang**
Fixing this return list: 
截圖 2021-05-12 上午1 38 53

### CODE REVIEW

**Comment by leofang** [comment]
I want to fix `norm`'s formatting as well:

截圖 2021-05-12 上午1 39 45

But the source code looks fine to me...Any ideas?

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @leofang!

**Comment by kgryte** [comment]
Re: `norm`. Not sure what is happening. I am seeing that the source formatting to be fine on my end. Possible that something is happening during doc generation. I'll go ahead and merge the current PR as is.

**Comment by leofang** [comment]
> Re: `norm`. Not sure what is happening. I am seeing that the source formatting to be fine on my end. Possible that something is happening during doc generation. I'll go ahead and merge the current PR as is.

Thanks, @kgryte. I fixed `norm` in #181.

**Pull request merged**
