### PR TITLE
Revert "Specify behavior of statistical reductions over the empty set"

### PR DESCRIPTION
**Pull request by Psoffie009**
Reverts data-apis/array-api#262

### CODE REVIEW

**Comment by kgryte** [comment]
@Psoffie009 Perhaps you can explain a bit more the rationale behind this PR.

**Comment by kgryte** [comment]
This appears to be a bot.

**Comment by asmeurer** [comment]
The same bot has also left some spammy comments on other issues. I would suggest blocking and reporting them to GitHub. 

There seems to be a strange influx of unusual bots recently. Another bot on NumPy a few weeks ago exactly copied one of @honno's issues word for word. I'm not really sure what the point of such bots is. My best guess is that they are trying to create a bunch of innocuous comments on GitHub which they can later edit to include SEO spam.

**Comment by rgommers** [comment]
> The same bot has also left some spammy comments on other issues. I would suggest blocking and reporting them to GitHub.

done, and will delete the other comments.

**Pull request closed without merging**
